version = 1

[*]
jinja = true
fit = on
parallel = 1

[qwen3.6-35b-a3b-iq2-xxs-5070]
# Sustituye esta ruta por la ubicación real de tu GGUF.
m = E:\models\Qwen_Qwen3.6-35B-A3B-IQ2_XXS.gguf
frequency-penalty = 0
min-p = 0
batch-size = 128
ubatch-size = 128
ctx-size = 8192
presence-penalty = 0
repeat-penalty = 1
temp = 0.6
top-k = 20
top-p = 0.95
flash-attn = on
cache-type-k = q8_0
cache-type-v = q8_0
n-gpu-layers = auto
n-predict = 2048

[gemma4-26b-a4b-5070]
# Sustituye esta ruta por la ubicación real de tu GGUF.
m = E:\models\gemma-4-26B-A4B-it-Q4_K_M.gguf
frequency-penalty = 0
min-p = 0
batch-size = 128
ubatch-size = 128
ctx-size = 8192
presence-penalty = 0
repeat-penalty = 1
temp = 1
top-k = 64
top-p = 0.95
flash-attn = on
cache-type-k = q8_0
cache-type-v = q8_0
n-gpu-layers = auto
n-predict = 2048
